### ISSUE TITLE
metanode access

### ISSUE THREAD

**Issue by m-grimes** [cytoscape/cyREST#18]
The metaNodePlugin2 plugin
http://www.rbvi.ucsf.edu/cytoscape/groups/
According to Scooter Morris:
    "metanodes are now part of the Cytoscape 3 core (just called groups).  They should certainly be available via CyREST."
These could be very useful if accessible through CyREST. 
Should this be an RCy3 feature request?
--Mark

**Comment by dotasek** [comment]
After looking into this, here are some notes:

* CyREST supports groups, which is indeed what metanodes became. Look under the _Groups_ tag in the CyREST API, or _group_ tag in the CyREST Command API.
* CyREST's groups endpoints fail with 404 errors, which there's a fix being implemented for, all now outlined in #28
