### ISSUE TITLE
Get layouts from apps such as yFiles

### ISSUE THREAD

**Issue by kmace** [cytoscape/cyREST#36]
Is it possible to expose non-standard layouts offered by apps such as yFiles?

**Comment by kmace** [comment]
FYI, I am using Rcy3, but I believe the issue is with CyREST rather than in Rcy3

**Comment by bdemchak** [comment]
By agreement with yWorks (owner of yFiles), access is only via mouse and
keyboard.

Barry Demchak -- from my mobile phone

**Comment by yGuy** [comment]
Hey there! yFiles developer here. It's true that for the app on the cytoscape app store there is no technical and legal option to expose the layouts provided by our library through cytoscape to third parties.  
That doesn't mean, though that you cannot use the yFiles layouts at all. 
The layouts come as part of a generic programming library and as such can be used from any program if you have a license for the (commercial) yFiles library. 
That would mean that you could create your own version of the yFiles layouts app for your specific Cytoscape application. The fact that this would give you full access to the huge and powerful programming API of yFiles would also mean that you can do a lot more than what the current App allows you to do: You would be able to configure the layout algorithms to a very high-degree: You could apply different settings for each and every element in your diagram, configure whether you are interested in speed or quality, etc.
You would not be allowed to create an application that provides these services to third parties, though; so you could not create another yFiles app, just without that limitation. Our standard license terms do not allow wrapping of our APIs, so you would only be allowed to use it for your application. If you are interested in the details, feel free to contact our sales team. They will be happy to discuss the licensing options with you: sales@yworks.com

Happy diagramming!

**Comment by dotasek** [comment]
Since I think the status of yFiles in Cytoscape Automation is pretty clear by now, I'm marking this as closed.
