### ISSUE TITLE
Network visual properties doesn't have expected PUT statement

### ISSUE THREAD

**Issue by dotasek** [cytoscape/cyREST#45]
Via @AlexanderPico:

We have "get /v1/networks/{networkId}/views/{viewId}/network/{visualProperty}”, but I don’t see the corresponding PUT.

**Comment by dotasek** [comment]
Update and expansion: this endpoint is also missing delete, as well as equivalent bypass management.

So, if we were to make this consistent with the existing API, the endpoints would look like this:

get /v1/networks/{networkId}/views/{viewId}/network/{visualProperty}
put /v1/networks/{networkId}/views/{viewId}/network/{visualProperty}
delete /v1/networks/{networkId}/views/{viewId}/network/{visualProperty}

get /v1/networks/{networkId}/views/{viewId}/network/{visualProperty}/bypass
put /v1/networks/{networkId}/views/{viewId}/network/{visualProperty}/bypass
delete /v1/networks/{networkId}/views/{viewId}/network/{visualProperty}/bypass

**Comment by AlexanderPico** [comment]
+1

**Comment by dotasek** [comment]
One more detail... the regular put statement (not the bypass one) has proven problematic to similar endpoints in the past. People expect it to behave pretty much exactly as the bypass one does, but it doesn't: it changes the visual property temporarily, and then gets overridden by the Visual Style when the network refreshes.

@AlexanderPico, I believe I'll leave the put out, and implement only the bypass methods.

**Comment by dotasek** [comment]
Addressed in 706a930f387a2e554bdfcff8be0f5e036dadd038

Awaiting release
