### ISSUE TITLE
set_attribute misses Implementation Notes in swagger

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/cyREST#50]
http://localhost:1234/v1/swaggerUI/swagger-ui/index.html?url=http://localhost:1234/v1/commands/swagger.json#!/network/network_set_attribute

**Comment by dotasek** [comment]
Since this issue relates to the command implementation, this issue will be handled by (http://code.cytoscape.org/redmine/issues/4117) and closed here.
