### ISSUE TITLE
Layout to prevent node overlap when network is created command line

### ISSUE THREAD

**Issue by Niveda-S** [cytoscape/cyREST#97]
Hi,

I've noticed that creating a network on cytoscape using igraph and py2cytoscape causes nodes to overlap over one another. Is there a way to prevent this via command line?

Thanks!

**Comment by AlexanderPico** [comment]
I think you have to follow with a layout. In the CyREST API doc, you'll find a section on `Layouts`. You can also find layout commands. See Help>Automation for both sets of API docs.
